{% set version = "0.9.0" %}
{% set sha256 = "3cfb480f31d757d2133676fffcade83230062052eba55421087af867fe044e8f" %}

package:
    name: bqplot
    version: {{ version }}

source:
    fn: bqplot-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
    sha256: {{ sha256  }}

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=6.0.0,<7.0.0
        - traitlets >=4.3.0
        - traittypes >=0.0.6
        - numpy >=1.10.4
        - pandas

test:
    imports:
        - bqplot

about:
    home: https://github.com/bloomberg/bqplot
    license: Apache 2.0
    summary: Plotting library for Jupyter

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
