{% set version = "0.11.8" %}
{% set sha256 = "ea9bf98cc4137ec12db48d6f6481b513d642bd196df04c3142c8a6815af125f8" %}

package:
    name: bqplot
    version: {{ version }}

source:
    fn: bqplot-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
    sha256: {{ sha256  }}

build:
    number: 0
    script: python -m pip install --no-deps --ignore-installed .
    noarch: python

requirements:
    host:
        - python
        - setuptools
        - jupyter
        - pip
    run:
        - python
        - ipywidgets >=7.0.0,<8.0
        - traitlets >=4.3.0,<5.0
        - traittypes >=0.0.6
        - numpy >=1.10.4
        - pandas

test:
    imports:
        - bqplot

about:
    home: https://github.com/bloomberg/bqplot
    license: Apache 2.0
    license_file: LICENSE
    license_family: Apache
    summary: Plotting library for Jupyter
    description: Plotting library for Jupyter
    doc_url: https://bqplot.readthedocs.io
    dev_url: https://github.com/bloomberg/bqplot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - rmenegaux
