{% set version = "0.12.43" %}
{% set sha256 = "f2b469d1f03df4f51873cb0406a24b56cdf4a835fc5aa9560776fc636b8b3449" %}

package:
  name: bqplot
  version: {{ version }}

source:
  fn: bqplot-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python  >=3.6
    - setuptools
    - jupyter
    - jupyter-packaging >=0.7.9
    - pip
  run:
    - python  >=3.6
    - ipywidgets >=7.6.0,<9
    - traitlets >=4.3.0,<6.0
    - traittypes >=0.0.6
    - numpy >=1.10.4
    - pandas >=1.0.0,<3.0.0

test:
  requires:
    - pip
  imports:
    - bqplot
  commands:
    - pip check
    - test -f ${PREFIX}/share/jupyter/nbextensions/bqplot/extension.js                           # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/bqplot/index.js                               # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/bqplot/package.json                          # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\bqplot\\extension.js exit 1           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\bqplot\\index.js exit 1               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\bqplot\\package.json exit 1          # [win]

about:
  home: https://github.com/bloomberg/bqplot
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Plotting library for Jupyter
  description: Plotting library for Jupyter
  doc_url: https://bqplot.readthedocs.io
  dev_url: https://github.com/bloomberg/bqplot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - rmenegaux
    - ChakriCherukuri
    - ibdafna
    - martinRenou
    - kaiayoung
