{% set version = "0.12.33" %}

package:
  name: bqplot
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bqplot/bqplot-{{ version }}.tar.gz
  sha256: a37f94752f01e75dd431c2f62c7849c28ad7020105121852816d2903d8b92c3e

build:
  number: 1
  script:
    - {{ PYTHON }} -c '__import__("shutil").rmtree("tests")'
    - {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - pip
    - python >=3.6
  run:
    - ipywidgets >=7.6.0,<8.0
    - numpy >=1.10.4
    - pandas
    - python >=3.6
    - traitlets >=4.3.0,<6.0
    - traittypes >=0.0.6

test:
  requires:
    - jupyterlab >=3,<4
    - m2-grep  # [win]
    - pip
  imports:
    - bqplot
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "bqplot.*OK" labextensions
    - jupyter nbextension list
    - jupyter nbextension list 1>nbextensions 2>&1
    - grep -iE "bqplot.*enabled" nbextensions

about:
  home: https://github.com/bloomberg/bqplot
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Plotting library for Jupyter
  description: Plotting library for Jupyter
  doc_url: https://bqplot.readthedocs.io
  dev_url: https://github.com/bloomberg/bqplot

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jasongrout
    - rmenegaux
    - ChakriCherukuri
    - ibdafna
    - martinRenou
    - kaiayoung
