travis:
  secure:
    BINSTAR_TOKEN: NRjLwf2PFER8ROFey45lvQ8ngNdGs7+seVpZdUKU3d32lY6GG+awESJDvDuco/PlA14/p0Y05zBV/eZURJUOqlZ0bUvzFVanOBYREjiH3rUs4TC/d3rql4XI0brwpz/AtoUqj9N4osNDUaivw7XDe34ZPzTdUfvjPXdZcU5CLul6zLSJ2om93BVVcNpPWzXQsPi4XjbzrsKYjNULu635pgWwwQ4mUrvIuSMTjzJ/LkQLK5y0/QN8W5qkA8DA46AEeOc0jgFuoqcZ/h3QFwfpIAh7UqK+Bo9biUJobwhuGiqMVmzOSdgVxAuIqMoD2rsF0JAa8rQgvg/ajPzFZhKykqWyRYPHTM02rthouIPcoeX8aT+6DqCdphMpoh8ljSoR+h7+v12yHSsNpREBuuPfrrfL+TCdeQEIwEFvvpEf32zzxEk25OzHjoZH+dMrHdAExw2hHnjx/Gvpyo/ZGtJeI8lOta78bSLV7vcTfkvFEA9ZFpU+6PHSczeGS7pftCiymPFOvioOP9ZOuedcgL5nzGLdsBVxfOLXAjQF0PLp1ILWseiUXNAB+P7QR8ux1oJr06bnpIBHBX9vo55DUAdoErMV6/GqXNPV4hXtctqCDY3Ui95NyCyI1H5Hu79XEjU7KUTzwuIXpR9Dz+i0Jx+S+O1nRwZS7oR3L9LlyPtjGtY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
